baseURL = "https://quinnw7.github.io/blog/"
languageCode = "en-us"
theme = "ananke"
title = "Quinn's Blog"
publishDir = "docs"  # 将生成的文件输出到 docs/ 目录

[params]
recent_posts_number = 7  # 首页显示的最新文章数量
body_classes = "garamond bg-near-white"
mainSections = ["tech", "read","stock","life-coach"]

[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Tech"
url = "/tech"
weight = 2
[[menu.main]]
name = "Read"
url = "/read"
weight = 3
[[menu.main]]
name = "Stock"
url = "/stock"
weight = 4
[[menu.main]]
name = "Life Coach"
url = "/life_coach"
weight = 5
[[menu.main]]
name = "Diary"
url = "/diary"
weight = 6
[[menu.main]]
name = "Product"
url = "/product"
weight = 7


